### ISSUE TITLE
Deequ for Spark 3.3.0

### ISSUE THREAD

**Issue by 10hith** [awslabs/deequ#437] opened 2022-10-07 11:01 UTC
Just checking to see if there is a release slated for Spark 3.3.0

**Comment by raghachellappa** [comment] 2022-11-01 15:53
We too (in our project) are looking for a version of Deequ that is compatible with Spark 3.3.0. Is there any timelines/tentative ETA for this? Will appreciate any details on this.

**Comment by giovannipapini-agilelab** [comment] 2022-11-08 15:24
Same here, is there any news?

**Comment by shehzad-qureshi** [comment] 2022-12-08 23:13
duplicate of #442 . we're working on cutting an official release soon.

**Closed by shehzad-qureshi** 2022-12-08 23:13 UTC

**Comment by lsgrep** [comment] 2023-01-30 13:43
@shehzad-qureshi  Hi Thank you very much for the work. Is there a release date for the 3.3.0 official release?

**Comment by shehzad-qureshi** [comment] 2023-01-30 20:04
apologies for the delay. 3.3.0 has been released to maven and has been tagged in this repo.
