### ISSUE TITLE
Example of `has_size` usage in java

### ISSUE THREAD

**Issue by sbaltus** [awslabs/deequ#124] opened 2019-08-12 20:14 UTC
Hi there, 
Still trying to evaluate deequ, I fail to use the `hasSize` (or similar).
Could you by any chance provide with an example of its usage in java ? 
Based on the function doc [here](https://github.com/awslabs/deequ/blob/81ddef5c7a3fc3af8610f6e9a3bd417756e2ebf2/src/main/scala/com/amazon/deequ/checks/Check.scala#L87), I've tried to use a lambda like :
```
 .hasSize(size-> (int) size == 5, Option.empty())
```
But I had the following runtime exception : 
```
Error:(38, 25) java: incompatible types: scala.Function1 is not a functional interface
    multiple non-overriding abstract methods found in interface scala.Function1
```
I'm using `java 8`, `spark 2.2.2` and `scala 2.11.2`. 
Many thanks, 

Stephanie

**Comment by sscdotopen** [comment] 2019-08-12 22:39
I have never tried this myself, but this might help with implementing scala functions in Java: https://stackoverflow.com/questions/25623779/implementing-a-scala-function-in-java

**Comment by poterius** [comment] 2019-08-14 11:13
@sbaltus 
Do you look for scala sample? How about this?
use "=>" instead of "->"

scala> var vs = VerificationSuite().onData(dataset).addCheck(Check(CheckLevel.Error, "Review Check").hasSize{size => size == 5}).run()
19/08/14 20:09:29 WARN AuthorizerExtension: Unable to create ranger policy cache directory at /etc/ranger/common_auth/policycache
vs: com.amazon.deequ.VerificationResult = VerificationResult(Error,Map(Check(Error,Review Check,List(SizeConstraint(Size(None)))) -> CheckResult(Check(Error,Review Check,List(SizeConstraint(Size(None)))),Error,List(ConstraintResult(SizeConstraint(Size(None)),Failure,Some(Value: 115667607 does not meet the constraint requirement!),Some(DoubleMetric(Dataset,Size,*,Success(1.15667607E8))))))),Map(Size(None) -> DoubleMetric(Dataset,Size,*,Success(1.15667607E8))))

**Comment by sbaltus** [comment] 2019-08-14 12:31
Hi there, 
Thanks @sscdotopen I'll try this approach. 
@poterius thanks for your help, unfortunately, I'm trying to run a `VerificationSuite` in java, so I'm looking for java sample.

**Comment by sbaltus** [comment] 2019-08-15 14:12
:wave: Solved this using an anonymous function :  
```
.hasSize(new scala.runtime.AbstractFunction1<Object, Object>() {
    @Override
    public Object apply(Object size) { return (long)size == 10; }
}, Option.empty())
```
Posting here if it can help anyone.

**Comment by sscdotopen** [comment] 2019-08-15 14:13
Happy to hear that it worked!

**Comment by iamsteps** [comment] 2019-08-15 14:24
Hi Stephanie,

glad that it seems to work for you. When reproducing the issue you were facing, I tried a similar approach (by bringing in [scala-java8-compat](https://github.com/scala/scala-java8-compat), and wrapping the Java lambda expression with `func`). With this I was able compile the code, but the metrics computation failed eventually. More precisely, the `VerificationResult` contained the failure indicating a `MetricsCalculationRuntimeException` due to an `IllegalArgumentException` which I believe is due to the constraint of having to rely on a generic function `Function1<Object,Object>`.

Would you be able to double check that the `VerificationResult` you are generating with your above code indeed indicates successful evaluation of the constraint? Please let me know.

**Comment by sbaltus** [comment] 2019-08-15 15:02
Hi Stephen, 

I've just tried using `scala-java8-compat` (which I didn't know about so thanks for this).
I've updated my code to : ` .hasSize(func(size-> (long)size == 10), Option.empty())` and I have a `Success`  as `VerificationResult.status()` .

**Comment by iamsteps** [comment] 2019-08-15 15:12
That's awesome! Strangely, the exact same approach doesn't work for me. Would you mind sharing your testing code (or maybe only the Deequ-related lines)? Then I could more easily trace back the reason for the failure in my setup, and eventually add your code to our documentation as an example for others how to use Deequ from Java. Thanks a lot!

**Comment by sbaltus** [comment] 2019-08-15 16:07
Here's my code for the `VerificationSuite` : 
```
Seq<Constraint> cons = new ArraySeq<>(0);
VerificationResult vr = new VerificationSuite().onData(logData)
        .addCheck(new Check(CheckLevel.Error(), "unit test", cons)
                .isPositive("_c2")
                .isComplete("_c0", Option.empty())
                .hasSize(func(size-> (long)size == 10), Option.empty())
        )
        .addCheck(new Check(CheckLevel.Warning(), "unit test", cons)
                .isComplete("_c1", Option.empty())
                .isNonNegative("_c3", Option.empty())
                .isUnique("_c1", Option.empty())
        ).run();

Seq<Check> checkSeq = new ArraySeq<>(0);
if (vr.status() != CheckStatus.Error()) {
    Dataset<Row> vrr = vr.checkResultsAsDataFrame(spark, vr, checkSeq);
    vrr.show(false);
}
```
Since I'm planning on testing a lot of deequ's features, I'm willing to contribute some code samples if it can help other java users.

**Comment by Arjav96** [comment] 2019-08-22 10:53
I am trying to use following maven dependency in Java:
`
    <groupId>org.scala-lang.modules</groupId>
    <artifactId>scala-java8-compat_2.13</artifactId>
    <version>0.9.0</version>
`
Using this version, I am getting compilation error for `func(size-> (long)size == 10)`  and also func() is marked as deprecated in this version.

I have checked using anonymous function thats working.

Help appreciated!
Thanks.

**Comment by sscdotopen** [comment] 2019-08-22 12:07
Hi Arjav,

Deequ is built for Scala 2.11, so you should try to use a dependency that has been built for that Scala version as well.

Best,
Sebastian

**Comment by Arjav96** [comment] 2019-08-22 12:14
Thanks Sebastian, my bad i haven't checked the version.
Its working now.

**Comment by sscdotopen** [comment] 2019-08-22 12:21
Happy to hear that!

**Closed by sscdotopen** 2019-08-22 12:21 UTC

**Comment by adronamraju** [comment] 2020-08-12 07:00
@sscdotopen @sbaltus  Im trying to evaluate Deequ in java as well. Im trying to covert the below code into java. Could you please post any suggestions.
val analysis = Analysis()
    .addAnalyzer(Size())
