### ISSUE TITLE
Spark 3.0 Support?

### ISSUE THREAD

**Issue by cmworkman** [awslabs/deequ#283] opened 2020-08-25 20:25 UTC
Our org has grown to love Deequ.  We have workloads that from a performance standpoint really stand to benefit from Spark 3.0.  It appears Deequ isn't compatible with Scala 2.12 and Spark 3.0.  Are there any plans to add support for Spark 3.0?

**Comment by sscdotopen** [comment] 2020-08-27 10:16
It would be very important for Deequ to support Spark 3. I am not with Amazon anymore unfortunately and I don't have the time and resources to work on that. @TammoR @dustin-lange would you be able to chime in here?

**Comment by danielyinanc** [comment] 2020-09-04 16:27
Yeah, this will be fantastic.

**Comment by Teej42** [comment] 2020-10-28 18:25
Is this being worked on?  Which branch is this being worked on?  Would outside contributions be accepted for this effort?

**Comment by Teej42** [comment] 2020-10-28 18:29
Looks like it's already done here - #286

**Comment by tooptoop4** [comment] 2020-10-29 23:23
do you know when next release is @sscdotopen ?

**Comment by Mika24** [comment] 2020-10-29 23:30
I would also like to upgrade to Spark 3.0. Look forward for the next release.

The error I run into is
"An error occurred while calling None.com.amazon.deequ.checks.Check.
: java.lang.NoClassDefFoundError: scala/Product$class
	at com.amazon.deequ.checks.Check.<init>(Check.scala:61)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:250)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)"

**Comment by Teej42** [comment] 2020-10-30 00:22
@Mika24 That is specific to Scala 2.12 support.  For some odd reason, if you use Scala 2.12 with Spark 2.x, it will not work either (throwing the same error).  Unfortunately, Spark 3.x is Scala 2.12 only.

So yes, this fix will be required to enable Spark 3.x support.

**Comment by Mika24** [comment] 2020-10-30 00:31
@Teej42 Thanks for the information. Really helps! Will just wait for the release then.

**Comment by sscdotopen** [comment] 2020-10-30 06:25
@tdhd @TammoR @iamsteps do you have time to cut a release? Ideally one that also contains a Spark 3 version?

**Comment by tooptoop4** [comment] 2020-10-30 08:34
@sscdotopen seems above comment (https://github.com/awslabs/deequ/issues/283#issuecomment-719081527) says that there is still a bug preventing spark3

**Comment by sscdotopen** [comment] 2020-10-30 09:10
It's not a bug, Spark 2.x is not compatible with Scala 2.12.

**Comment by sscdotopen** [comment] 2020-10-30 09:12
Or do I get this wrong? We need to have the appropriate build profiles in place so that Spark 2.x and Scala 2.11 are used or Spark 3x. and Scala 2.12

**Comment by aviatesk** [comment] 2020-10-30 10:41
I'm not familiar with [maven build profiles](https://maven.apache.org/guides/introduction/introduction-to-profiles.html), but as far as I understands, it's mostly used for local build while specifying various versions of dependencies (and Scala itself), right ? I don't know if it's possible to release all the profile combinations in maven repositories. @radford1 , could you tell us your idea on this ?

**Comment by Teej42** [comment] 2020-10-30 11:46
Okay, here's the clarification:  Spark 2.x is built with either Scala 2.11 (by default - i.e.: spark-2.4.7-bin-without-hadoop.tgz) or Scala 2.12 (i.e.: spark-2.4.7-bin-without-hadoop-scala-2.12.tgz).  Spark 3.x is built with Scala 2.12 by default.  There are no known Spark 3.x binaries built with Scala 2.11 available on Apache.

The error message that was reported [here](https://github.com/awslabs/deequ/issues/283#issuecomment-719081527) occurs when you attempt to run the current working version of Deequ against any specific Spark versions that is built using Scala 2.12.

It is expected that this [issue](https://github.com/awslabs/deequ/issues/283) we are having the conversation in, will resolve this particular error message, and any other error messages that is associated with Scala 2.12 support for Spark.

**Comment by sscdotopen** [comment] 2020-10-31 07:41
It seems to be that there is still work need in the pom.xml files. The build profiles only specify the spark version to use, but they additionally need to specify the scala version. @cmworkman could you prepare a PR to update this?

**Comment by iatsukanov** [comment] 2020-12-23 04:54
Even with the changes that were merged into master recently it impossible to use Spark3.0. 

1. Dependency id with a typo, in the readme -
```
libraryDependencies += "com.amazon.deequ" % "deequ" % "1.1.0-spark-3.0-scala-2.12"
```
whereas the real one with an underscore - `1.1.0_spark` - https://repo1.maven.org/maven2/com/amazon/deequ/deequ/1.1.0_spark-3.0-scala-2.12/

2. If you try to compile `1.1.0_spark-3.0-scala-2.12` with spark3.0 you will get
```
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: org.apache.spark:spark-launcher, org.apache.spark:spark-sketch, org.apache.spark:spark-kvstore, org.json4s:json4s-ast, org.apache.spark:spark-catalyst, org.apache.spark:spark-network-shuffle, com.twitter:chill, org.apache.spark:spark-sql, org.scala-lang.modules:scala-xml, org.json4s:json4s-jackson, com.fasterxml.jackson.module:jackson-module-scala, org.json4s:json4s-core, org.apache.spark:spark-unsafe, org.json4s:json4s-scalap, org.scala-lang.modules:scala-parser-combinators, org.apache.spark:spark-tags, org.apache.spark:spark-core, org.apache.spark:spark-network-common
```
it can be reproduced via `build.sbt`
```
name := "deequ-spark3.0"
version := "0.1"
scalaVersion := "2.12.12"
libraryDependencies += "com.amazon.deequ" % "deequ" % "1.1.0_spark-3.0-scala-2.12"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.0.0"
```
and the command `sbt compile`

**Comment by CarterKilgour** [comment] 2021-01-19 02:10
@iatsukanov inspired by the post [here](https://github.com/Azure/azure-cosmosdb-spark/issues/239) I was able to get around this issue with the following:

`libraryDependencies += "org.apache.spark" %% "spark-core" % "3.1.0"  % "provided"
 libraryDependencies +=  "org.apache.spark" %% "spark-sql".   % "3.0.1" % "provided"
 libraryDependencies += "com.amazon.deequ" % "deequ"         % "1.0.5" % "provided" exclude("org.apache.spark", "spark-core_2.11") exclude("org.apache.spark", "spark-sql_2.11")
`

**Comment by lange-labs** [comment] 2021-06-09 11:21
Closing due to inactivity; Spark 3 now officially supported

**Closed by lange-labs** 2021-06-09 11:21 UTC

**Comment by shuvamx99** [comment] 2022-06-09 11:10
Having trouble loading deequ in Spark 3.2.1 and Scala version 2.13.8.
What do I need to add in the build.sbt file?

**Comment by shuvamx99** [comment] 2022-06-09 11:20
This is the error I am getting: Exception in thread "main" java.lang.NoClassDefFoundError: com/amazon/deequ/checks/Check
	at deequ5.main(Main.scala)
I used this in my build.sbt

libraryDependencies += "org.apache.spark"  %% "spark-core"  % "3.1.0" % "provided"
libraryDependencies +=  "org.apache.spark" %% "spark-sql"   % "3.0.1" % "provided"
libraryDependencies += "com.amazon.deequ"  % "deequ"        % "1.1.0_spark-3.0-scala-2.12" % "provided" exclude("org.apache.spark", "spark-core_2.11") exclude("org.apache.spark", "spark-sql_2.11")
