### ISSUE TITLE
Using Deequ with zeppelin

### ISSUE THREAD

**Issue by gautamk** [awslabs/deequ#93] opened 2019-03-08 21:41 UTC
Not sure if this is a Zeppelin related issue or not, 
But I get the following error, I'm using zeppelin 0.8.1, with spark 2.4, scala version version 2.11.12 running on AWS EMR.

	java.lang.NoSuchMethodError: scala.reflect.internal.Symbols$Symbol.originalEnclosingMethod()Lscala/reflect/internal/Symbols$Symbol; 
		at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.getEnclosingMethodAttribute(GenASM.scala:1306) 
		at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1222) 
		at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.emitFor$1(GenASM.scala:135) 
		at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:141) 
		at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1625) 
		at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1610) 
		at scala.tools.nsc.Global$Run.compileSources(Global.scala:1605) 
		at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:388) 
		at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:804) 
		at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:763) 
		at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:627) 
		at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:664) 
		at scala.tools.nsc.interpreter.IMain$$anonfun$quietBind$1.apply(IMain.scala:663) 
		at scala.tools.nsc.interpreter.IMain$$anonfun$quietBind$1.apply(IMain.scala:663) 
		at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:202) 
		at scala.tools.nsc.interpreter.IMain.quietBind(IMain.scala:663) 
		at org.apache.zeppelin.spark.SparkScala211Interpreter$.loopPostInit$1(SparkScala211Interpreter.scala:179) 
		at org.apache.zeppelin.spark.SparkScala211Interpreter$.org$apache$zeppelin$spark$SparkScala211Interpreter$$loopPostInit(SparkScala211Interpreter.scala:214) 
		at org.apache.zeppelin.spark.SparkScala211Interpreter.open(SparkScala211Interpreter.scala:86) 
		at org.apache.zeppelin.spark.NewSparkInterpreter.open(NewSparkInterpreter.java:102) 
		at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:62) 
		at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:69) 
		at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:617) 
		at org.apache.zeppelin.scheduler.Job.run(Job.java:188) 
		at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:140) 
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) 
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
		at java.lang.Thread.run(Thread.java:748)

<img src="https://imgur.com/download/PMswwyr"/>

**Comment by sscdotopen** [comment] 2019-03-11 14:21
Hi Gautam, this looks more like an error related to Scala. Which Scala version are you using?

**Comment by gautamk** [comment] 2019-03-11 19:23
I'm using scala 2.11.12

**Comment by sscdotopen** [comment] 2019-03-14 11:28
It seems this is indeed a problem with Spark 2.4. Thanks for pointing this out, we will look into the problem.

**Comment by iamsteps** [comment] 2019-05-21 13:04
Gautam, thanks a lot for bringing this to our attention and apologies for the delay.

First of all, Deequ supports both Spark 2.4 as well as Scala 2.11.12.

However, I was able to reproduce the issue you just described. While I don't have a complete explanation for the observed behavior, it seems to come down to the way Zeppelin is handling external dependencies. I reproduced the error by adding Deequ as a dependency via the Zeppelin UI by adding the artifact `com.amazon.deequ:deequ:1.0.1` as dependency in the UI via Settings - Interpreter - spark - edit. Subsequent import of `com.amazon.deequ.VerificationSuite` (or for what it's worth any class, for example also `org.apache.spark.sql.DataFrame`) leads to error message you posted previously.

The positive news is that I was able to run Deequ in an identical setting (EMR 5.23.0, Spark 2.4, Zeppelin 0.8.1, Scala 2.11.12) by declaring the dependency on Deequ within the notebook itself in code. To do this, start with a fresh Zeppelin instance (i.e. without adding the dependency via the UI), and in a new notebook execute the following code before anything else:

```
%dep
z.load("com.amazon.deequ:deequ:1.0.1")
```

followed by your code using Deequ, e.g.

```
case class Item(...)

val rdd = spark.sparkContext.parallelize(...)

val data = spark.createDataFrame(rdd)

import com.amazon.deequ.VerificationSuite
import com.amazon.deequ.checks.{Check, CheckLevel}

val verificationResult = VerificationSuite().onData(data).addCheck(....).run()
```

This gives you a working environment for Deequ. As this approach works, I suspect the original issue to be an issue with Zeppelin. Since we have a workaround using the `%dep` directive, I will close this issue. Please reopen it in case you encounter problems or the workaround does not work for you.

**Closed by iamsteps** 2019-05-21 13:04 UTC
